import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(22C468C2-F5FA-499B-827A-9C0B5B9A0A56)
]

interface IMath : IUnknown
{
	HRESULT Add(long nAdd1, long nAdd2, long* pnAdd);
	HRESULT Sub(long nSub1, long nSub2, long* pnSub);
}

[
	uuid(039C536A-7C99-4A8D-91FD-9796DE059294)
]

coclass Math
{
	interface IMath;
}